### ISSUE TITLE
Are you planning to include a pipeline template definition in a future release?

### ISSUE THREAD

**Issue by bjsun** [ketan/gocd-groovy-dsl-config-plugin#1]
The pipeline contains duplicate definitions in difference branch, which can be simplified if the template is distinguished by the form of variables.

**Comment by ketan** [comment]
Are you looking to define a gocd template using a config repo plugin — OR — are you trying to reuse groovy code within the same repository to define similar pipelines?

**Comment by ketan** [comment]
Are you looking for the equivalent of this issue https://github.com/tomzo/gocd-yaml-config-plugin/issues/2 implemented here?
